### ISSUE TITLE
It is not issue but question

### ISSUE THREAD

**Issue by piotrbukalski** [Elgom/WindowsStoreServices#1]
How did you find out that this uri will give you list of apps?
https://manage.devcenter.microsoft.com/v1.0/my/analytics/applicationlist

I couldn't find anything about listing all apps in official documentation.

**Comment by TimLariviere** [comment]
Hi.
You're right, there isn't anything about this uri in any documentation.
I found out by checking how the official Dev Center app was retrieving all my published apps.
Turned out to be really easy. Would've been great to mention it in the official documentation...

**Comment by piotrbukalski** [comment]
Thank you for answer. It's a shame that Microsoft didn't provide more in this api... I'm glad that I found your implementation, and this little trick. Thank you! :)
